### ISSUE TITLE
支持调用自己的yso

### ISSUE THREAD

**Issue by cwkiller** [4ra1n/mysql-fake-server#2]
自带的链太少了，而且没有回显以及内存马支持，是否可以添加自定义yso，或者把su18的yso集成进去

**Comment by 4ra1n** [comment]
感谢师傅的建议，我之后看一下怎么支持自定义yso

**Comment by 4ra1n** [comment]
正在想办法支持这个功能

**Comment by 4ra1n** [comment]
试用下 0.0.3 版本，如果有 bug 可以再反馈
